/* Generated By:JavaCC: Do not edit this line. ScenarioParserConstants.java */
package endgame.input.syntax;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ScenarioParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 5;
  /** RegularExpression Id. */
  int DASH = 6;
  /** RegularExpression Id. */
  int COLON = 7;
  /** RegularExpression Id. */
  int COMMA = 8;
  /** RegularExpression Id. */
  int COMMA_SPACE = 9;
  /** RegularExpression Id. */
  int UNDERSCORE = 10;
  /** RegularExpression Id. */
  int BLOCK_START = 11;
  /** RegularExpression Id. */
  int BLOCK_END = 12;
  /** RegularExpression Id. */
  int EQUALS = 13;
  /** RegularExpression Id. */
  int QUOTE = 14;
  /** RegularExpression Id. */
  int STARRY_DATE = 15;
  /** RegularExpression Id. */
  int ELLIPSIS = 16;
  /** RegularExpression Id. */
  int PIPE = 17;
  /** RegularExpression Id. */
  int SPACES = 18;
  /** RegularExpression Id. */
  int DD = 19;
  /** RegularExpression Id. */
  int MM = 20;
  /** RegularExpression Id. */
  int YYYY = 21;
  /** RegularExpression Id. */
  int YYYY_MM_DD = 22;
  /** RegularExpression Id. */
  int YYYY_MM = 23;
  /** RegularExpression Id. */
  int MM_DD = 24;
  /** RegularExpression Id. */
  int DATE_LIST = 25;
  /** RegularExpression Id. */
  int WHEN_CONTROL = 26;
  /** RegularExpression Id. */
  int WHEN_LIST = 27;
  /** RegularExpression Id. */
  int WHEN = 28;
  /** RegularExpression Id. */
  int DATE_RANGE = 29;
  /** RegularExpression Id. */
  int DOUBLE = 30;
  /** RegularExpression Id. */
  int NUM = 31;
  /** RegularExpression Id. */
  int PERCENT_LIST = 32;
  /** RegularExpression Id. */
  int PERCENT = 33;
  /** RegularExpression Id. */
  int MONEY_RANGE = 34;
  /** RegularExpression Id. */
  int MONEY = 35;
  /** RegularExpression Id. */
  int WHOLE_DOLLARS = 36;
  /** RegularExpression Id. */
  int FRACTION = 37;
  /** RegularExpression Id. */
  int PENNIES = 38;
  /** RegularExpression Id. */
  int DIGIT = 39;
  /** RegularExpression Id. */
  int QUOTED_TEXT = 40;
  /** RegularExpression Id. */
  int BANK = 41;
  /** RegularExpression Id. */
  int RIF = 42;
  /** RegularExpression Id. */
  int TFSA = 43;
  /** RegularExpression Id. */
  int NRA = 44;
  /** RegularExpression Id. */
  int PROV_TERR = 45;
  /** RegularExpression Id. */
  int SPEND_BANK_BALANCE_ABOVE = 46;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<COMMENT>",
    "\"-\"",
    "\":\"",
    "\",\"",
    "<COMMA_SPACE>",
    "\"_\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\"\\\"\"",
    "\"*-\"",
    "\"..\"",
    "\"|\"",
    "<SPACES>",
    "<DD>",
    "<MM>",
    "<YYYY>",
    "<YYYY_MM_DD>",
    "<YYYY_MM>",
    "<MM_DD>",
    "<DATE_LIST>",
    "<WHEN_CONTROL>",
    "<WHEN_LIST>",
    "<WHEN>",
    "<DATE_RANGE>",
    "<DOUBLE>",
    "<NUM>",
    "<PERCENT_LIST>",
    "<PERCENT>",
    "<MONEY_RANGE>",
    "<MONEY>",
    "<WHOLE_DOLLARS>",
    "<FRACTION>",
    "<PENNIES>",
    "<DIGIT>",
    "<QUOTED_TEXT>",
    "\"bank\"",
    "\"rif\"",
    "\"tfsa\"",
    "\"nra\"",
    "<PROV_TERR>",
    "\"spend-bank-balance-above\"",
    "\"syntax-version\"",
    "\"v1.0.0\"",
    "\"description\"",
    "\"project-root\"",
    "\"number-of-iterations\"",
    "\"date-of-birth\"",
    "\"annual-test-for-survival\"",
    "\"simulation-start-date\"",
    "\"simulation-end-date\"",
    "\"sex\"",
    "\"male\"",
    "\"female\"",
    "\"federal-tax\"",
    "\"initial-year\"",
    "\"personal-amount\"",
    "\"personal-amount-additional\"",
    "\"personal-amount-threshold\"",
    "\"age-amount\"",
    "\"age-amount-threshold\"",
    "\"pension-income-max\"",
    "\"standard-retirement-age\"",
    "\"taxable-capital-gain-fraction\"",
    "\"dividend-tax-credit-numer\"",
    "\"dividend-tax-credit-denom\"",
    "\"tax-brackets\"",
    "\"rif-withholding-tax-brackets\"",
    "\"provincial-tax\"",
    "\"jurisdiction\"",
    "\"personal-amount-supplement\"",
    "\"personal-amount-rate\"",
    "\"ageAmtSupplement\"",
    "\"ageAmtSupplementThreshold\"",
    "\"ageAmtSupplementRate\"",
    "\"dividend-gross-up-mult\"",
    "\"low-income-basic\"",
    "\"low-income-age\"",
    "\"low-income-threshold\"",
    "\"low-income-rate\"",
    "\"age-tax-credit\"",
    "\"age-tax-credit-threshold\"",
    "\"surtax-threshold-1\"",
    "\"surtax-rate-1\"",
    "\"surtax-threshold-2\"",
    "\"surtax-rate-2\"",
    "\"schedule-b-threshold\"",
    "\"schedule-b-rate\"",
    "\"live-alone-amount\"",
    "\"pension-income-rate\"",
    "\"health-premium-tax-brackets\"",
    "\"stocks\"",
    "\"price\"",
    "\"dividend\"",
    "\"amount\"",
    "\"growth\"",
    "\"update-stock-prices\"",
    "\"fixed\"",
    "\"range\"",
    "\"gaussian\"",
    "\"mean\"",
    "\"std-dev\"",
    "\"explicit-list\"",
    "\"stock-commission\"",
    "\"fixed-percent\"",
    "\"fixed-amount\"",
    "\"custom-schedule\"",
    "\"tfsa-room\"",
    "\"initial-room\"",
    "\"yearly-limit\"",
    "\"rif-minimum-withdrawals\"",
    "\"accounts\"",
    "\"cash\"",
    "\"small-balance-limit\"",
    "\"convert-rsp-to-rif\"",
    "\"stock-positions\"",
    "\"stock-book-values\"",
    "\"gic-positions\"",
    "\"-year\"",
    "\"matures\"",
    "\"sequential-liquidation\"",
    "\"avoid-downturn-years\"",
    "\"account-sequence\"",
    "\"stock-sequence\"",
    "\"sell\"",
    "\"annual-tfsa-top-up\"",
    "\"transactions {\"",
    "\"sweep-cash-from\"",
    "\"bank-debit-credit\"",
    "\"year-zero-amounts\"",
    "\"net-income-before-adjustments\"",
    "\"net-income\"",
    "\"oas-income\"",
    "\"employment-income\"",
    "\"oas\"",
    "\"monthly-amount-at-65\"",
    "\"start-month\"",
    "\"payment-day\"",
    "\"clawback-threshold\"",
    "\"clawback-percent\"",
    "\"monthly-reward\"",
    "\"boost-age\"",
    "\"boost-percent\"",
    "\"start-window-begin\"",
    "\"start-window-end\"",
    "\"gis-employment-exemption\"",
    "\"cpp\"",
    "\"nominal-monthly-amount\"",
    "\"monthly-penalty\"",
    "\"start-nominal\"",
    "\"survivor-benefit-amount\"",
    "\"survivor-benefit-start\"",
    "\"buy-stock\"",
    "\"sell-stock\"",
    "\"shares\"",
    "\"buy-gic\"",
    "\"transfer-stock-in\"",
    "\"transfer-stock-out\"",
    "\"move-stock\"",
    "\"from\"",
    "\"to\"",
    "\"small-employment\"",
    "\"start-date\"",
    "\"stop-date\"",
    "\"gross-monthly-income\"",
    "\"paid-on\"",
    "\"annuity-payment\"",
    "\"stock-split\"",
    "\"-to-1\"",
  };

}
